version: '3'

services:
  library:
    image: fsdapps/library-service:0.0.1-SNAPSHOT
    container_name: library-service
    ports:
    - 9999
    environment:
    - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
    - fsd

networks:
  fsd:
    driver: bridge